//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_SchoolTime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolTimeEntities : DbContext
    {
        public SchoolTimeEntities()
            : base("name=SchoolTimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableArbitor> TableArbitor { get; set; }
        public virtual DbSet<TableEcole> TableEcole { get; set; }
        public virtual DbSet<TableTechnicien> TableTechnicien { get; set; }
        public virtual DbSet<TableCalHeure> TableCalHeure { get; set; }
        public virtual DbSet<TableCalSave> TableCalSave { get; set; }
    }
}
