//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_SchoolTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableCalSave
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string Technicien { get; set; }
        public string Lieu { get; set; }
        public Nullable<double> Ticket { get; set; }
        public int Temps { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
